apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-skaffold
spec:
  template:
    spec:
      containers:
        - image: nginx-skaffold
          name: nginx-skaffold
          imagePullPolicy: IfNotPresent
