apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-skaffold
  name: nginx-skaffold
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-skaffold-config
      containers:
        - name: nginx-skaffold
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/nginx.conf
              name: config